[project]
name = "openwebui-haystack-orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=1.0.0",
    "fastapi>=0.136.1",
    "fastembed-haystack>=2.3.0",
    "hayhooks[chainlit]>=1.19.1",
    "haystack-ai>=2.29.0",
    "loguru>=0.7.3",
    "ollama>=0.6.2",
    "ollama-haystack>=6.3.0",
    "pytest>=9.0.3",
    "pypdf>=5.4.0",
    "pyyaml>=6.0.1",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.18.0",
    "qdrant-haystack>=10.3.0",
    "requests>=2.32.0",
    "ruff>=0.15.13",
    "sentence-transformers>=5.5.1",
    "uvicorn>=0.47.0",
]
